### ISSUE TITLE
`release.json` TBC flavor might be rejected by add-on managers

### ISSUE THREAD

**Issue by layday** [NinerBull/NPCRPGossip#1]
Hi there - I maintain https://github.com/layday/github-wow-addon-catalogue, a script which catalogues WoW add-ons hosted on GH.  I noticed that my script failed to parse the `release.json` file both of this add-on and [tRP3_RPNameInQuests](https://github.com/NinerBull/tRP3_RPNameInQuests).  The reason was that the TBC flavor value is `tbc`, whereas the one defined in the BigWigs packager is [`bcc`](https://github.com/BigWigsMods/packager/blob/f8a8e9e77439b3ff38bc1b57dd43e61a0f30a351/release.sh#L78).  Add-on managers will most likely have based their implementation on the BW packager and might not be able to install NPCRPGossip or tRP3_RPNameInQuests for TBC - or at all, if they validate the release metadata.

**Comment by NinerBull** [comment]
Fixed with today's release, thank you!
